version: "2"
services:
  elasticsearch:
    image: "elasticsearch:5.2"
    ports: 
      - "9200:9200"
  grafana:
    image: "grafana/grafana:4.1.1"
    depends_on:
      - elasticsearch
    ports: 
      - "3000:3000"