version: "2"
services:
  elasticsearch:
    image: "elasticsearch"
    ports: 
      - "9200:9200"
    command: [-E, http.cors.enabled=true, -E, http.cors.allow-origin=*]
  grafana:
    image: "grafana/grafana"
    depends_on:
      - elasticsearch
    ports: 
      - "3000:3000"
    network_mode: "host"